//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigEntry.gig {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkItem", Namespace="http://schemas.datacontract.org/2004/07/ContentTypes")]
    [System.SerializableAttribute()]
    public partial class LinkItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime m_dateEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime m_dateStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long m_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime m_dateEnd {
            get {
                return this.m_dateEndField;
            }
            set {
                if ((this.m_dateEndField.Equals(value) != true)) {
                    this.m_dateEndField = value;
                    this.RaisePropertyChanged("m_dateEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime m_dateStart {
            get {
                return this.m_dateStartField;
            }
            set {
                if ((this.m_dateStartField.Equals(value) != true)) {
                    this.m_dateStartField = value;
                    this.RaisePropertyChanged("m_dateStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_description {
            get {
                return this.m_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.m_descriptionField, value) != true)) {
                    this.m_descriptionField = value;
                    this.RaisePropertyChanged("m_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long m_id {
            get {
                return this.m_idField;
            }
            set {
                if ((this.m_idField.Equals(value) != true)) {
                    this.m_idField = value;
                    this.RaisePropertyChanged("m_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_title {
            get {
                return this.m_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.m_titleField, value) != true)) {
                    this.m_titleField = value;
                    this.RaisePropertyChanged("m_title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_url {
            get {
                return this.m_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.m_urlField, value) != true)) {
                    this.m_urlField = value;
                    this.RaisePropertyChanged("m_url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="gig.GigManagerServiceContract", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface GigManagerServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/GigManagerServiceContract/SaveGig", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/GigManagerServiceContract/SaveGigRe" +
            "sponse")]
        void SaveGig(GigEntry.gig.LinkItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/GigManagerServiceContract/GetGig", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/GigManagerServiceContract/GetGigRes" +
            "ponse")]
        GigEntry.gig.LinkItem GetGig();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface GigManagerServiceContractChannel : GigEntry.gig.GigManagerServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GigManagerServiceContractClient : System.ServiceModel.ClientBase<GigEntry.gig.GigManagerServiceContract>, GigEntry.gig.GigManagerServiceContract {
        
        public GigManagerServiceContractClient() {
        }
        
        public GigManagerServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GigManagerServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GigManagerServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GigManagerServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveGig(GigEntry.gig.LinkItem item) {
            base.Channel.SaveGig(item);
        }
        
        public GigEntry.gig.LinkItem GetGig() {
            return base.Channel.GetGig();
        }
    }
}
